apiVersion: v1
kind: Service
metadata:
  name: character-service
  namespace: dnd-services
  labels:
    app: character-service
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: web
      protocol: TCP
      name: http
  selector:
    app: character-service
