global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "campaign-service"
    scrape_interval: 10s
    static_configs:
      - targets: ["campaign:8000"]
    metrics_path: "/metrics"

  - job_name: "campaign-postgres"
    static_configs:
      - targets: ["postgres:5432"]

  - job_name: "campaign-rabbitmq"
    static_configs:
      - targets: ["rabbitmq:15672"]
    metrics_path: "/api/metrics"
    basic_auth:
      username: campaign_user
      password: campaign_pass
