version: '3.8'

services:
  campaign-service:
    build: .
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/campaign-service
      - MESSAGE_HUB_URL=http://message-hub:8200
      - AUTH_SERVICE_URL=http://auth-service:8300
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    networks:
      - dnd_network

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=campaign-service
    volumes:
      - campaign-service_data:/var/lib/postgresql/data
    networks:
      - dnd_network

  redis:
    image: redis:7
    networks:
      - dnd_network

volumes:
  campaign-service_data:

networks:
  dnd_network:
    external: true
