version: '3.8'

services:
  # Frontend React application
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  # Backend FastAPI application
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - ollama
      - stable_diffusion
    volumes:
      - ./backend:/app
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/
      - OLLAMA_API_URL=http://ollama:11434/api
      - SD_API_URL=http://stable_diffusion:7860/api

  # MongoDB database
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  # Ollama container with Llama 3
  ollama:
    build: ./ai_services/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: >
      sh -c "ollama serve & sleep 5 && ollama pull llama3:8b && tail -f /dev/null"

  # Stable Diffusion container
  stable_diffusion:
    build: ./ai_services/stable_diffusion
    ports:
      - "7860:7860"
    volumes:
      - sd_data:/root/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  mongodb_data:
  ollama_data:
  sd_data: