"""add user_id and campaign_id fields

Revision ID: 2025_09_01_01
Revises: 892e3e90a36b
Create Date: 2025-09-01 15:33:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2025_09_01_01'
down_revision: str = '892e3e90a36b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('user_id', sa.dialects.postgresql.UUID(as_uuid=True), nullable=False))
    op.add_column('characters', sa.Column('campaign_id', sa.dialects.postgresql.UUID(as_uuid=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'campaign_id')
    op.drop_column('characters', 'user_id')
    # ### end Alembic commands ###
