[project]
name = "character-service"
version = "0.1.0"
description = "D&D Character Creation and Management Service"
authors = ["OpenSourceLoot <dnd@opensourceloot.dev>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "win-64"]

[tasks]
start = "uvicorn character_service.main:app --host 0.0.0.0 --port 8000 --reload"
test = "pytest tests/ -v"
lint = "flake8 src/ tests/"
format = "black src/ tests/"
typecheck = "mypy src/ tests/"
coverage = "pytest --cov=src/ tests/ -v"
docs = "mkdocs serve"

[dependencies]
python = ">=3.10,<3.11"
fastapi = ">=0.100.0,<1.0"
uvicorn = ">=0.22.0,<1.0"
sqlalchemy = ">=2.0.0,<3.0"
pydantic = ">=2.0.0,<3.0"
alembic = ">=1.11.0,<2.0"
psycopg2-binary = ">=2.9.0,<3.0"
httpx = ">=0.24.0,<1.0"
python-jose = ">=3.3.0,<4.0"
python-multipart = ">=0.0.6,<1.0"
redis = ">=4.6.0,<5.0"
prometheus-client = ">=0.17.0,<1.0"
python-dotenv = ">=1.0.0,<2.0"

[environments.test]
dependencies = [
    "pytest>=7.4.0,<8.0",
    "pytest-cov>=4.1.0,<5.0",
    "pytest-asyncio>=0.21.0,<1.0"
]

[environments.dev]
dependencies = [
    "flake8>=6.0.0,<7.0",
    "black>=23.7.0,<24.0",
    "mypy>=1.4.0,<2.0"
]

[environments.docs]
dependencies = [
    "mkdocs>=1.5.0,<2.0",
    "mkdocs-material>=9.1.0,<10.0"
]
