[project]
name = "character"
version = "0.1.0"
description = "Character creation and management service for D&D Character Creator"
authors = ["Your Name <your.email@example.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "win-64"]

[tasks]
start = "uvicorn character.main:app --host 0.0.0.0 --port 8000 --reload"
test = "pytest tests/ --cov=character --cov-report=term-missing --cov-report=xml -v"
format = { cmd = ["black", ".", "isort", "."] }
lint = { cmd = ["ruff", "check", ".", "black", "--check", ".", "isort", "--check-only", "."] }
type-check = "mypy ."
migrate = { cmd = ["alembic", "upgrade", "head"] }
create-migration = { cmd = ["alembic", "revision", "--autogenerate", "-m"] }
shell = "ipython"

[dependencies]
# Core Framework
python = "==3.11"
fastapi = "==0.115.6"
uvicorn = {version = "==0.32.1", extras = ["standard"]}

# Core Database Support
sqlalchemy = "==2.0.23"
alembic = "==1.12.1"
psycopg2-binary = "==2.9.9"
asyncpg = "==0.29.0"
aiosqlite = "==0.19.0"

# Data Validation & Serialization
pydantic = "==2.11.7"
pydantic-settings = "==2.6.1"

# HTTP Client for LLM APIs
httpx = "==0.28.1"
requests = "==2.31.0"

# AI/LLM Services
openai = "==1.58.1"
ollama = "==0.5.1"

# Security & Authentication
python-jose = {version = "==3.3.0", features = ["cryptography"]}
passlib = {version = "==1.7.4", features = ["bcrypt"]}
python-multipart = "==0.0.6"

# Configuration Management
python-dotenv = "==1.0.0"

# Logging
structlog = "==23.2.0"

# Performance Monitoring
prometheus-client = "==0.19.0"
psutil = "==5.9.6"

# Redis Cache
redis = "*"
aioredis = "*"

[dev-dependencies]
pytest = "*"
pytest-cov = "*"
pytest-asyncio = "*"
black = "*"
isort = "*"
ruff = "*"
mypy = "*"
ipython = "*"
httpx = "*"
factory-boy = "*"

[feature.dev]
dependencies = [
    "pytest",
    "pytest-cov",
    "pytest-asyncio",
    "black",
    "isort",
    "ruff",
    "mypy",
    "ipython",
    "httpx",
    "factory-boy"
]

[feature.prod]
dependencies = [
    "gunicorn",
    "uvicorn[standard]"
]

[environments]
default = "dev"

[environments.dev]
features = ["dev"]

[environments.prod]
features = ["prod"]
