# Campaign Service Configuration

server:
  port: 8001
  host: 0.0.0.0
  workers: 2
  timeout: 30

message_hub:
  url: http://message-hub:8200
  timeout: 5s
  health_check:
    path: /health
    interval: 10s
    timeout: 5s
    threshold: 3

database:
  type: postgresql
  host: campaign-db
  port: 5432
  name: campaign_db
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  pool_size: 10
  max_overflow: 5

llm:
  service_url: http://llm-service:8100
  timeout: 60s
  cache_ttl: 3600  # 1 hour
  retry:
    max_attempts: 3
    backoff_factor: 2

campaign_settings:
  max_players: 8
  default_language: en
  session_duration_limit: 86400  # 24 hours in seconds
  inactive_timeout: 1800  # 30 minutes in seconds
  auto_save_interval: 300  # 5 minutes in seconds

monitoring:
  metrics_enabled: true
  log_level: info
  log_format: json
  metrics_port: 8002

caching:
  enabled: true
  type: redis
  redis:
    host: redis
    port: 6379
    db: 1
  ttl: 3600  # 1 hour
  max_size: 1000

events:
  enabled: true
  types:
    - campaign_created
    - campaign_updated
    - campaign_deleted
    - player_joined
    - player_left
    - session_started
    - session_ended
  batch_size: 100
  retry:
    max_attempts: 3
    backoff_factor: 2

chat:
  enabled: true
  message_history_limit: 1000
  max_message_length: 2000
  supported_formats:
    - text
    - dice_roll
    - character_action
    - dm_note

storage:
  map_assets:
    path: /app/assets/maps
    allowed_types: [png, jpg, jpeg, webp]
    max_size: 10485760  # 10MB
  character_sheets:
    path: /app/assets/sheets
    allowed_types: [pdf, png]
    max_size: 5242880  # 5MB
