"""create initial tables

Revision ID: 892e3e90a36b
Revises: 
Create Date: 2025-09-01 11:11:40.255297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '892e3e90a36b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.dialects.postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('species', sa.String(), nullable=False),
    sa.Column('background', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('character_classes', sa.JSON(), nullable=False),
    sa.Column('ability_scores', sa.JSON(), nullable=False),
    sa.Column('equipment', sa.JSON(), nullable=False),
    sa.Column('spells_known', sa.JSON(), nullable=False),
    sa.Column('spells_prepared', sa.JSON(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('racial_bonuses', sa.JSON(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('hit_points', sa.Integer(), nullable=False),
    sa.Column('armor_class', sa.Integer(), nullable=False),
    sa.Column('proficiency_bonus', sa.Integer(), nullable=False),
    sa.Column('spell_save_dc', sa.Integer(), nullable=True),
    sa.Column('spellcasting_ability', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('characters')
    # ### end Alembic commands ###
