# Character Service Configuration

# Service Information
service:
  name: character_service
  version: "2.0.0"
  description: "D&D Character Creation and Management Service"

# API Configuration
api:
  version: "v1"
  title: "D&D Character Service"
  description: "Character Creation and Management for D&D 5e 2024"
  docs_url: "/docs"
  redoc_url: "/redoc"
  openapi_url: "/openapi.json"

# CORS Configuration
cors:
  origins: ["*"]
  allow_credentials: true
  allow_methods: ["*"]
  allow_headers: ["*"]

# Database Configuration
database:
  type: postgresql
  pool_size: 20
  max_overflow: 10
  pool_timeout: 30
  pool_recycle: 1800
  connect_timeout: 10
  echo: false

# Message Hub Integration
message_hub:
  heartbeat_interval: 30
  retry_interval: 5
  max_retries: 3
  timeout: 10

# LLM Service Configuration
llm:
  default_model: gpt-4
  fallback_model: gpt-3.5-turbo
  timeout: 30
  max_tokens: 2000
  temperature: 0.7
  retry_attempts: 3
  backoff_factor: 2

# Image Service Integration
image:
  timeout: 30
  max_retries: 3
  formats: ["png", "jpg", "webp"]
  max_size: 5242880  # 5MB

# Catalog Service Integration
catalog:
  timeout: 10
  max_retries: 3
  cache_ttl: 3600

# Cache Configuration
cache:
  type: redis
  prefix: "char_svc:"
  ttl: 3600
  connection_pool: 20

# Logging Configuration
logging:
  level: INFO
  format: json
  file_path: "/var/log/character_service.log"
  max_size: 100  # MB
  backup_count: 10
  console_logging: true

# Metrics Configuration
metrics:
  enabled: true
  collection_interval: 15
  retention_days: 30
  labels:
    environment: development
    service: character_service

# Health Check Configuration
health:
  enabled: true
  interval: 30
  timeout: 5
  failures_threshold: 3

# Security Configuration
security:
  secret_key_length: 32
  password_min_length: 8
  token_expiry: 3600
  max_login_attempts: 5
  lockout_duration: 300

# Feature Flags
features:
  antitheticon_enabled: true
  journal_system: true
  version_control: true
  content_generation: true
