api:
  dashboard: true  # Enable dashboard only in development
  insecure: false  # Dashboard security

entryPoints:
  web:
    address: ":80"
    http:
      redirections:  # Force HTTPS
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: internal
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: "admin@dndcreator.com"
      storage: "/etc/traefik/acme/acme.json"
      httpChallenge:
        entryPoint: web

metrics:
  prometheus:
    buckets: [0.1, 0.3, 1.2, 5.0]
    addEntryPointsLabels: true
    addServicesLabels: true

log:
  level: INFO
  format: json

accessLog:
  format: json
  fields:
    headers:
      defaultMode: keep
      names:
        User-Agent: keep
        Authorization: redact
        X-API-Key: redact
