# API Gateway Service Configuration

server:
  port: 8080
  host: 0.0.0.0
  workers: 4
  timeout: 30

message_hub:
  url: http://message-hub:8200
  timeout: 5s
  health_check:
    path: /health
    interval: 10s
    timeout: 5s
    threshold: 3

authentication:
  jwt:
    secret_key: ${JWT_SECRET_KEY}
    algorithm: HS256
    access_token_expire_minutes: 30
    refresh_token_expire_days: 7
  
  api_key:
    header_name: X-API-Key
    key_prefix: dnd_
    rate_limit:
      requests_per_minute: 100
      burst: 20

routing:
  character:
    service: character-service
    base_path: /character
    strip_path: true
    rewrite_target: /api/v1/character
    methods: [GET, POST, PUT, DELETE]
    timeout: 30s
    rate_limit:
      requests_per_minute: 60
      burst: 10

  campaign:
    service: campaign-service
    base_path: /campaign
    strip_path: true
    rewrite_target: /api/v1/campaign
    methods: [GET, POST, PUT, DELETE]
    timeout: 30s
    rate_limit:
      requests_per_minute: 30
      burst: 5

  image:
    service: image-service
    base_path: /image
    strip_path: true
    rewrite_target: /api/v1/image
    methods: [GET, POST, PUT, DELETE]
    timeout: 45s
    rate_limit:
      requests_per_minute: 20
      burst: 3

circuit_breaker:
  default:
    failure_threshold: 5
    reset_timeout: 60s
    half_open_requests: 3
  
  custom:
    character-service:
      failure_threshold: 3
      reset_timeout: 30s
      half_open_requests: 2

cors:
  allow_origins: ["*"]  # Configure appropriately for production
  allow_methods: ["*"]
  allow_headers: ["*"]
  allow_credentials: true
  max_age: 600  # 10 minutes

monitoring:
  metrics_enabled: true
  log_level: info
  log_format: json
  metrics_port: 8081

security:
  tls_enabled: true
  min_tls_version: "1.2"
  ssl_ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256"
  hsts_enabled: true
  hsts_max_age: 31536000  # 1 year
  frame_deny: true
  content_type_nosniff: true
  xss_protection: true
  rate_limit:
    global:
      requests_per_minute: 1000
      burst: 100
