api:
  dashboard: true  # Disable in production
  insecure: true  # Disable in production

log:
  level: INFO

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: dnd_network

  file:
    directory: "/etc/traefik"
    watch: true

entryPoints:
  web:
    address: ":80"
    # Uncomment for production to redirect to HTTPS
    # http:
    #   redirections:
    #     entryPoint:
    #       to: websecure
    #       scheme: https

  websecure:
    address: ":443"
    # Uncomment for production
    # http:
    #   tls:
    #     certResolver: letsencrypt

# Uncomment for production
# certificatesResolvers:
#   letsencrypt:
#     acme:
#       email: your-email@example.com
#       storage: /etc/traefik/acme.json
#       httpChallenge:
#         entryPoint: web
