[project]
name = "storage"
version = "0.1.0"
description = "Service for D&D Character Creator"
authors = ["Your Name <your.email@example.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "win-64"]

[tasks]
start = "uvicorn storage.main:app --host 0.0.0.0 --port 8301 --reload"
test = "pytest tests/ --cov=storage --cov-report=term-missing --cov-report=xml -v"
format = { cmd = ["black", ".", "isort", "."] }
lint = { cmd = ["ruff", "check", ".", "black", "--check", ".", "isort", "--check-only", "."] }
type-check = "mypy ."
migrate = { cmd = ["alembic", "upgrade", "head"] }
create-migration = { cmd = ["alembic", "revision", "--autogenerate", "-m"] }
shell = "ipython"

[dependencies]
python = "==3.11"
fastapi = "*"
uvicorn = "*"
pydantic = "*"
pydantic-settings = "*"
python-json-logger = "*"
prometheus-client = "*"

# Database dependencies
sqlmodel = "*"
asyncpg = "*"
alembic = "*"

# Redis dependencies
aioredis = "*"
redis = "*"

# Celery dependencies


[dev-dependencies]
pytest = "*"
pytest-cov = "*"
pytest-asyncio = "*"
black = "*"
isort = "*"
ruff = "*"
mypy = "*"
ipython = "*"
httpx = "*"
factory-boy = "*"

[feature.dev]
dependencies = [
    "pytest",
    "pytest-cov",
    "pytest-asyncio",
    "black",
    "isort",
    "ruff",
    "mypy",
    "ipython",
    "httpx",
    "factory-boy"
]

[feature.prod]
dependencies = [
    "gunicorn",
    "uvicorn[standard]"
]

[environments]
default = "dev"

[environments.dev]
features = ["dev"]

[environments.prod]
features = ["prod"]
