version: "3.8"

services:
  game_session:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - MESSAGE_HUB_URL=http://message_hub:8200
      - STORAGE_SERVICE_URL=http://storage:8300
      - LOG_LEVEL=INFO
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - game_session_net

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - game_session_net

volumes:
  redis_data:

networks:
  game_session_net:
    name: game_session_net