# DEPRECATED: Use ../deployment/compose/backend-dev.yml instead
# This file is kept for backward compatibility

version: '3.8'

services:
  # PostgreSQL Database
  database:
    image: postgres:15-alpine
    container_name: dnd_character_db_legacy
    environment:
      POSTGRES_DB: dnd_characters
      POSTGRES_USER: dnd_user
      POSTGRES_PASSWORD: ${DB_PASSWORD:-change_this_password}
    volumes:
      - postgres_data_legacy:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - dnd_network_legacy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dnd_user -d dnd_characters"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Character Creator API
  api:
    build: 
      context: .
      dockerfile: Dockerfile.new
    container_name: dnd_character_api_legacy
    environment:
      # Database Configuration
      DATABASE_URL: postgresql://dnd_user:${DB_PASSWORD:-change_this_password}@database:5432/dnd_characters
      
      # LLM Configuration - Using local Ollama service
      LLM_PROVIDER: ${LLM_PROVIDER:-ollama}
      OLLAMA_API_URL: ${OLLAMA_API_URL:-http://host.containers.internal:11434/api}
      LLM_MODEL: ${LLM_MODEL:-llama3:8b}
      
      # External LLM APIs (if needed)
      OPENAI_API_KEY_FILE: /run/secrets/openai_api_key
      ANTHROPIC_API_KEY_FILE: /run/secrets/anthropic_api_key
      
      # API Configuration
      SECRET_KEY: ${SECRET_KEY:-your-secret-key-change-this-in-production}
      DEBUG: ${DEBUG:-false}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      
      # CORS Configuration
      CORS_ORIGINS: ${CORS_ORIGINS:-http://localhost:3000,http://localhost:8080}
      
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - dnd_network_legacy
    volumes:
      - ./logs:/app/logs
    secrets:
      - openai_api_key
      - anthropic_api_key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data_legacy:

networks:
  dnd_network_legacy:
    driver: bridge

# Secrets management for secure API key handling
secrets:
  openai_api_key:
    environment: "OPENAI_API_KEY"
  anthropic_api_key:
    environment: "ANTHROPIC_API_KEY"

# DEPRECATION NOTICE:
# This compose file is deprecated. Please use:
# - For full stack: ../podman-compose.yml
# - For backend development: ../deployment/compose/backend-dev.yml
