[project]
name = "message"
version = "0.1.0"
description = "Message Hub service for D&D Character Creator"
authors = ["Your Name <your.email@example.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "win-64"]

[tasks]
start = "uvicorn message.main:app --host 0.0.0.0 --port 8200 --reload"
test = "pytest tests/ --cov=message --cov-report=term-missing --cov-report=xml -v"
format = { cmd = ["black", ".", "isort", "."] }
lint = { cmd = ["ruff", "check", ".", "black", "--check", ".", "isort", "--check-only", "."] }
type-check = "mypy ."
migrate = { cmd = ["alembic", "upgrade", "head"] }
create-migration = { cmd = ["alembic", "revision", "--autogenerate", "-m"] }
shell = "ipython"

[dependencies]
# Core Framework
python = "==3.11"
fastapi = "==0.115.6"
uvicorn = {version = "==0.32.1", extras = ["standard"]}

# Message Queue and Pub/Sub
redis = "==5.0.1"
aio-pika = "==9.3.1"

# Circuit Breaker
circuitbreaker = "==1.4.0"

# HTTP Client
httpx = "==0.28.1"

# Event Store
sqlalchemy = "==2.0.23"
alembic = "==1.12.1"
asyncpg = "==0.29.0"

# Data Validation & Serialization
pydantic = "==2.11.7"
pydantic-settings = "==2.6.1"

# Monitoring & Logging
prometheus-client = "==0.19.0"
structlog = "==23.2.0"
opentelemetry-api = "==1.22.0"
opentelemetry-sdk = "==1.22.0"
opentelemetry-instrumentation-fastapi = "==0.43b0"

# Security & Configuration
python-jose = {version = "==3.3.0", features = ["cryptography"]}
python-dotenv = "==1.0.0"

[dev-dependencies]
pytest = "*"
pytest-cov = "*"
pytest-asyncio = "*"
black = "*"
isort = "*"
ruff = "*"
mypy = "*"
ipython = "*"
httpx = "*"
factory-boy = "*"

[feature.dev]
dependencies = [
    "pytest",
    "pytest-cov",
    "pytest-asyncio",
    "black",
    "isort",
    "ruff",
    "mypy",
    "ipython",
    "httpx",
    "factory-boy"
]

[feature.prod]
dependencies = [
    "gunicorn",
    "uvicorn[standard]"
]

[environments]
default = "dev"

[environments.dev]
features = ["dev"]

[environments.prod]
features = ["prod"]
