name: D&D Character Creator Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
    
    - name: Run database validation tests
      run: |
        cd /home/ajs7/dnd_tools/dnd_char_creator
        python -c "
        import sys
        sys.path.append('backend')
        from creation_validation import validate_all_databases
        result = validate_all_databases()
        print(f'Database validation: {result}')
        assert result, 'Database validation failed'
        "
    
    - name: Run character creation tests with OpenAI
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # This is how you use the secret
      run: |
        cd /home/ajs7/dnd_tools/dnd_char_creator
        python test_character_creation_simple.py
    
    - name: Run comprehensive character tests
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # Available as environment variable
      run: |
        cd /home/ajs7/dnd_tools/dnd_char_creator
        python test_comprehensive_character_creation.py
